# Generated by Django 6.0 on 2025-12-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        choices=[(5, "5%"), (10, "10%"), (15, "15%")]
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
